#!/bin/bash
# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Unlimited history
export HISTFILESIZE=
export HISTSIZE=
shopt -s histappend
shopt -s checkwinsize

exists() {
    command -v "$1" >/dev/null
    return $?
}

if exists git; then
    headhash() {  # $1 = max characters
        git branch &>/dev/null && echo "$(git rev-parse HEAD | head -c $1) "
    }
    headbranch() {
        git branch &>/dev/null && echo "$(git rev-parse --abbrev-ref HEAD) "
    }
    export PS1='\[\e[97m\]\u\[\e[91m\]@\[\e[97m\]\h \[\e[93m\]$(headhash 6)\[\e[92m\]$(headbranch)\[\e[96m\]\w\[\e[m\] '
else
    export PS1='\[\e[97m\]\u\[\e[91m\]@\[\e[97m\]\h \[\e[96m\]\w\[\e[m\] '
fi

if exists vim; then
    export EDITOR=vim
else
    export EDITOR=vi  # I mean, it's almost everywhere
fi

bashrc() {
    local path="$HOME/.bashrc"
    $EDITOR "$path"
    >&2 echo "Reloading bashrc"
    source "$path"
}

######### WORKS WITH COREUTILS #########

cdp () {
    cd -P -- "$1" 
}

alias ls="ls --color=auto"

mkcdir () {
    mkdir -p -- "$1" && cd -P -- "$1"
}

stopwatch() {
    date1=$(date +%s); while true; do
        echo -ne "$(date -u --date @$(($(date +%s) - date1)) +%H:%M:%S)\r";
    done
}


####### CONDITIONAL DECLARATIONS #######

if exists ansible; then
    # no cows!
    export ANSIBLE_NOCOWS=1
fi

if exists cal; then
    alias cal="cal -m"
fi

if exists clang; then
    export CC=clang
    export CXX=clang++
fi

if exists curl; then
    alias myip='curl ipinfo.io/ip'
fi

if exists dnf; then
    alias dnfi="sudo dnf install"
    alias dnfr="sudo dnf remove"
    alias dnfs="dnf search"
    alias dnfu="sudo dnf update"
fi

if exists grep; then
    hisgrep () {
        history | grep "$@"
    }
fi

if exists git; then
    alias gits='git status'
    alias gitas='git add . && git status'
    alias oneline='git log --oneline'
    ghclone () {
        git clone "https://github.com/$1/$2"
    }
fi

if exists i3; then
    alias i3c='vim ~/.i3/config'
    alias i3sc='vim ~/.i3status.conf'
fi

if exists morf; then
    # morf colors
    export PRETTY="color"
fi

if exists most; then
    # Color manual pages
    if exists man; then
        alias man="PAGER=most man"
    fi
    if exists sfdoc; then
        alias sfdoc="PAGER=most sfdoc"
    fi
fi

if exists pacman; then
    alias Syu='sudo pacman -Syu'
    alias Scc='sudo pacman -Scc'
    alias Sc='sudo pacman -Sc'
    alias Ss='pacman -Ss'
    alias S='sudo pacman -S'
    alias R='sudo pacman -R'
fi

if exists python3; then
    alias py3='python3'
fi

if exists rtorrent; then
    stty stop undef
    stty start undef
fi

if exists sudo; then
    alias fuck='sudo $(history -p \!\!)'
fi

if exists systemctl; then
    # No pager for systemctl
    export SYSTEMD_PAGER=
fi

if exists tmux; then
    alias tree="tree --color=auto"
fi

if exists tmux; then
    alias tmuxrc='vim ~/.tmux.conf'
fi

if exists vim; then
    alias vimp='vim -p *'
    alias vimrc="vim ~/.vimrc"
fi

if exists which; then
    src () {
        $EDITOR $(which "$1") 
    }
fi

if exists wifi-menu; then
    alias wifi-menu='sudo wifi-menu'
fi

if exists youtube-dl; then
    alias ytd='youtube-dl'
    alias ytx='youtube-dl --extract-audio --add-metadata --audio-format vorbis'
fi

if [ "$HOSTNAME" = deimos -o "$HOSTNAME" = enceladus ]; then
    export PS1='\[\e[93m\]\u\[\e[m\]@\h \[\e[93m\]$(headhash 6)\[\e[92m\]$(headbranch)\[\e[96m\]\w\[\e[m\] \[\e[93m\]\\$\[\e[m\] '
fi

if [ "$HOSTNAME" = localhost ]; then  # probably termux
    export PS1='\[\e[93m\]$(headhash 4)\[\e[92m\]$(headbranch)\[\e[93m\]\w\[\e[m\] \[\e[96m\]\\$\[\e[m\] '
    n() {
         local threshold=16
         local file=~/notes
         local lines

         if [ "$1" != "" ]; then
              echo "$@" >> $file
              return 0
         fi
         if [ ! -f $file ]; then
              echo " === no notes ==="
              return 1
         fi
         lines=$(cat $file | wc -l)
         if [ $(( $lines > $threshold )) = 1 ]; then
              echo " === last $threshold lines ==="
         fi
         tail -n $threshold $file
         return 0
    }

fi

if [ "$HOSTNAME" = redpad ]; then
    rover () {
        firefox --new-tab "https://rover.redhat.com/people/profile/$1"
    }
    alias pesdb='sudo docker start pesdb'
    alias django='PES_DEVEL=1 ./manage.py'
fi
