syntax on
set autoindent
set expandtab
set number
set relativenumber
set shiftwidth=4
set shiftwidth=4
set showcmd
set softtabstop=4
set softtabstop=4
set tabpagemax=100
set tabstop=4
set hlsearch

" colors for man pages
let $PAGER = 'most'

" bind w!! to get sudo rights and save file
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

" open help in a new tab instead of a split window
cnoremap help tab help
