syntax on
set autoindent
set expandtab
set number
set shiftwidth=4
set shiftwidth=4
set softtabstop=4
set softtabstop=4
set tabpagemax=100
set tabstop=4

" bash aliases and functions (mainly for my1mt)
let $BASH_ENV = "~/.bash_aliases"

" colors for man pages
let $PAGER = 'most'

" bind w!! to get sudo rights and save file
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!
